### ISSUE TITLE
Rules definitions

### ISSUE THREAD

**Issue by mmorel-35** [catenacyber/perfsprint#39]
The actual rules needs to clearly explicit to be easily understood and used by the users. This is a first draft that needs to be challenged to then enable the separation of concerns in the tool.

## error-format

```go
❌
fmt.Errorf("Simple message")
fmt.Sprintf("%s", err)
fmt.Sprintf("%v", err)

✅
errors.New("Simple message")
err.Error()
```

with:
 * `error-format.err-error` option equivalent to `err-error` to use `err.Error()` even if it is only equivalent for non-nil errors

## string-format

```go
❌
fmt.Sprintf("%s", strVal)
fmt.Sprintf("format string %s", strVal)
fmt.Sprintf("%s format string", strVal)

✅
strVal
"format string " + strVal
strVal + "format string"
```

with 
 * `string-format.concat` option equivalent to `strconcat` to enable strings concatenation

## bool-format

```go
❌
fmt.Sprintf("%t", boolVal)

✅
strconv.FormatBool(boolBal)
```

## hash-format

```go
❌
fmt.Sprintf("%x", hash)

✅
hex.EncodeToString(hash)
```

## integer-format

```go
❌
fmt.Sprintf("%d", id)
fmt.Sprintf("%v", version)

✅
strconv.Itoa(id)
strconv.FormatUint(uint64(version), 10)
```
with 
 * `integer-format.cast` option equivalent to `int-conversion` to enable int or uint type cast

**Comment by alexandear** [comment]
Please remember that we have to maximize compatibility with existing rules:

```yaml
  perfsprint:
    # Optimizes even if it requires an int or uint type cast.
    # Default: true
    int-conversion: false
    # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
    # Default: false
    err-error: true
    # Optimizes `fmt.Errorf`.
    # Default: true
    errorf: false
    # Optimizes `fmt.Sprintf` with only one argument.
    # Default: true
    sprintf1: false
    # Optimizes into strings concatenation.
    # Default: true
    strconcat: false
```

https://github.com/golangci/golangci-lint/blob/e0e37c43762068149116bcd69b305c1ca05647ae/.golangci.reference.yml#L2190

Maybe it is better to add simply only one `string-format` rule to cover format cases for all types `fmt.Sprintf("%t", boolVal), fmt.Sprintf("%x", hash), fmt.Sprintf("%d", id)`.
