### ISSUE TITLE
Support `-test=false` in golang linter

### ISSUE THREAD

**Issue by miparnisari** [catenacyber/perfsprint#40]
https://golangci-lint.run/usage/linters/#perfsprint

shows

```yaml
linters-settings:
  perfsprint:
    # Optimizes even if it requires an int or uint type cast.
    # Default: true
    int-conversion: false
    # Optimizes into `err.Error()` even if it is only equivalent for non-nil errors.
    # Default: false
    err-error: true
    # Optimizes `fmt.Errorf`.
    # Default: true
    errorf: false
    # Optimizes `fmt.Sprintf` with only one argument.
    # Default: true
    sprintf1: false
    # Optimizes into strings concatenation.
    # Default: true
    strconcat: false
```

I would like to see

```
  -test
        indicates whether test files should be analyzed, too (default true)
```

there, too.
