### ISSUE TITLE
Configuration support (good first issue)

### ISSUE THREAD

**Issue by Antonboom** [catenacyber/perfsprint#7]
Just so we don't forget the idea :)

**What (DRAFT):**
```yml
perfsprint:
  enabled:
    - string    # Just using string
    - error     # Just using Error()
    - bool      # strconv.FormatBool
    - hex       # hex.EncodeToString
    - int       # strconv.Itoa or strconv.FormatInt
    - uint      # strconv.FormatUint
  int:
      # Enable int and int64 only mode
      no-type-conversions: true
  uint:
      # Enable uint64 only mode
      no-type-conversions: true
```

**How to:**
https://github.com/catenacyber/perfsprint/pull/1#discussion_r1364375733
